In [1]:
import pandas as pd
import numpy as np
import os
import json

In [2]:
# folder_path='C:/Users/RSHIRINI/OneDrive - United Nations/Desktop/DSS/DATA COLLECTOR/datacollector_received_quest/recieved_quests'

#for health
folder_path='C:/Users/RSHIRINI/OneDrive - United Nations/Desktop/DSS/DATA COLLECTOR/datacollector_received_quest/health'
#check all xlsx files in the folder

xlsx_files = [f for f in os.listdir(folder_path) if f.endswith('.xlsx')]
xlsx_files

['algeria - Health_10.xlsx',
 'algeria - Health_11_a.xlsx',
 'algeria - Health_11_b.xlsx',
 'algeria - Health_12.xlsx',
 'algeria - Health_13.xlsx',
 'algeria - Health_14.xlsx',
 'algeria - Health_15.xlsx',
 'algeria - Health_16.xlsx',
 'algeria - Health_17.xlsx',
 'algeria - Health_18.xlsx',
 'algeria - Health_19.xlsx',
 'algeria - Health_1_a.xlsx',
 'algeria - Health_1_b.xlsx',
 'algeria - Health_2_a.xlsx',
 'algeria - Health_2_b.xlsx',
 'algeria - Health_3_a.xlsx',
 'algeria - Health_3_b.xlsx',
 'algeria - Health_4_a.xlsx',
 'algeria - Health_4_b.xlsx',
 'algeria - Health_4_c.xlsx',
 'algeria - Health_4_d.xlsx',
 'algeria - Health_4_e.xlsx',
 'algeria - Health_4_f.xlsx',
 'algeria - Health_5_a.xlsx',
 'algeria - Health_5_b.xlsx',
 'algeria - Health_5_c.xlsx',
 'algeria - Health_5_d.xlsx',
 'algeria - Health_5_e.xlsx',
 'algeria - Health_6.xlsx',
 'algeria - Health_7.xlsx',
 'algeria - Health_8.xlsx',
 'algeria - Health_9.xlsx',
 'bahrain - Health_10.xlsx',
 'bahrain - Health_11_a.xlsx',
 'bahrain - Health_11_b.xlsx',
 'bahrain - Health_12.xlsx',
 'bahrain - Health_13.xlsx',
 'bahrain - Health_14.xlsx',
 'bahrain - Health_15.xlsx',
 'bahrain - Health_16.xlsx',
 'bahrain - Health_17.xlsx',
 'bahrain - Health_18.xlsx',
 'bahrain - Health_19.xlsx',
 'bahrain - Health_1_a.xlsx',
 'bahrain - Health_1_b.xlsx',
 'bahrain - Health_2_a.xlsx',
 'bahrain - Health_2_b.xlsx',
 'bahrain - Health_3_a.xlsx',
 'bahrain - Health_3_b.xlsx',
 'bahrain - Health_4_a.xlsx',
 'bahrain - Health_4_b.xlsx',
 'bahrain - Health_4_c.xlsx',
 'bahrain - Health_4_d.xlsx',
 'bahrain - Health_4_e.xlsx',
 'bahrain - Health_4_f.xlsx',
 'bahrain - Health_5_a.xlsx',
 'bahrain - Health_5_b.xlsx',
 'bahrain - Health_5_c.xlsx',
 'bahrain - Health_5_d.xlsx',
 'bahrain - Health_5_e.xlsx',
 'bahrain - Health_6.xlsx',
 'bahrain - Health_7.xlsx',
 'bahrain - Health_8.xlsx',
 'bahrain - Health_9.xlsx',
 'comoros - Health_10.xlsx',
 'comoros - Health_11_a.xlsx',
 'comoros - Health_11_b.xlsx',
 'comoros - Health_12.xlsx',
 'comoros - Health_13.xlsx',
 'comoros - Health_14.xlsx',
 'comoros - Health_15.xlsx',
 'comoros - Health_16.xlsx',
 'comoros - Health_17.xlsx',
 'comoros - Health_18.xlsx',
 'comoros - Health_19.xlsx',
 'comoros - Health_1_a.xlsx',
 'comoros - Health_1_b.xlsx',
 'comoros - Health_2_a.xlsx',
 'comoros - Health_2_b.xlsx',
 'comoros - Health_3_a.xlsx',
 'comoros - Health_3_b.xlsx',
 'comoros - Health_4_a.xlsx',
 'comoros - Health_4_b.xlsx',
 'comoros - Health_4_c.xlsx',
 'comoros - Health_4_d.xlsx',
 'comoros - Health_4_e.xlsx',
 'comoros - Health_4_f.xlsx',
 'comoros - Health_5_a.xlsx',
 'comoros - Health_5_b.xlsx',
 'comoros - Health_5_c.xlsx',
 'comoros - Health_5_d.xlsx',
 'comoros - Health_5_e.xlsx',
 'comoros - Health_6.xlsx',
 'comoros - Health_7.xlsx',
 'comoros - Health_8.xlsx',
 'comoros - Health_9.xlsx',
 'djibouti - Health_10.xlsx',
 'djibouti - Health_11_a.xlsx',
 'djibouti - Health_11_b.xlsx',
 'djibouti - Health_12.xlsx',
 'djibouti - Health_13.xlsx',
 'djibouti - Health_14.xlsx',
 'djibouti - Health_15.xlsx',
 'djibouti - Health_16.xlsx',
 'djibouti - Health_17.xlsx',
 'djibouti - Health_18.xlsx',
 'djibouti - Health_19.xlsx',
 'djibouti - Health_1_a.xlsx',
 'djibouti - Health_1_b.xlsx',
 'djibouti - Health_2_a.xlsx',
 'djibouti - Health_2_b.xlsx',
 'djibouti - Health_3_a.xlsx',
 'djibouti - Health_3_b.xlsx',
 'djibouti - Health_4_a.xlsx',
 'djibouti - Health_4_b.xlsx',
 'djibouti - Health_4_c.xlsx',
 'djibouti - Health_4_d.xlsx',
 'djibouti - Health_4_e.xlsx',
 'djibouti - Health_4_f.xlsx',
 'djibouti - Health_5_a.xlsx',
 'djibouti - Health_5_b.xlsx',
 'djibouti - Health_5_c.xlsx',
 'djibouti - Health_5_d.xlsx',
 'djibouti - Health_5_e.xlsx',
 'djibouti - Health_6.xlsx',
 'djibouti - Health_7.xlsx',
 'djibouti - Health_8.xlsx',
 'djibouti - Health_9.xlsx',
 'egypt - Health_10.xlsx',
 'egypt - Health_11_a.xlsx',
 'egypt - Health_11_b.xlsx',
 'egypt - Health_12.xlsx',
 'egypt - Health_13.xlsx',
 'egypt - Health_14.xlsx',
 'egypt - Health_15.xlsx',
 'egypt - Health_16.xlsx',
 'egypt - Health_17.xlsx',
 'egypt - Health_18.xlsx',
 'egypt - Health_19.xlsx',
 'egypt - Health_1_a.xlsx',
 'egypt - Health_1_b.xlsx',
 'egypt - Health_2_a.xlsx',
 'egypt - Health_2_b.xlsx',
 'egypt - Health_3_a.xlsx',
 'egypt - Health_3_b.xlsx',
 'egypt - Health_4_a.xlsx',
 'egypt - Health_4_b.xlsx',
 'egypt - Health_4_c.xlsx',
 'egypt - Health_4_d.xlsx',
 'egypt - Health_4_e.xlsx',
 'egypt - Health_4_f.xlsx',
 'egypt - Health_5_a.xlsx',
 'egypt - Health_5_b.xlsx',
 'egypt - Health_5_c.xlsx',
 'egypt - Health_5_d.xlsx',
 'egypt - Health_5_e.xlsx',
 'egypt - Health_6.xlsx',
 'egypt - Health_7.xlsx',
 'egypt - Health_8.xlsx',
 'egypt - Health_9.xlsx',
 'iraq - Health_10.xlsx',
 'iraq - Health_11_a.xlsx',
 'iraq - Health_11_b.xlsx',
 'iraq - Health_12.xlsx',
 'iraq - Health_13.xlsx',
 'iraq - Health_14.xlsx',
 'iraq - Health_15.xlsx',
 'iraq - Health_16.xlsx',
 'iraq - Health_17.xlsx',
 'iraq - Health_18.xlsx',
 'iraq - Health_19.xlsx',
 'iraq - Health_1_a.xlsx',
 'iraq - Health_1_b.xlsx',
 'iraq - Health_2_a.xlsx',
 'iraq - Health_2_b.xlsx',
 'iraq - Health_3_a.xlsx',
 'iraq - Health_3_b.xlsx',
 'iraq - Health_4_a.xlsx',
 'iraq - Health_4_b.xlsx',
 'iraq - Health_4_c.xlsx',
 'iraq - Health_4_d.xlsx',
 'iraq - Health_4_e.xlsx',
 'iraq - Health_4_f.xlsx',
 'iraq - Health_5_a.xlsx',
 'iraq - Health_5_b.xlsx',
 'iraq - Health_5_c.xlsx',
 'iraq - Health_5_d.xlsx',
 'iraq - Health_5_e.xlsx',
 'iraq - Health_6.xlsx',
 'iraq - Health_7.xlsx',
 'iraq - Health_8.xlsx',
 'iraq - Health_9.xlsx',
 'jordan - Health_10.xlsx',
 'jordan - Health_11_a.xlsx',
 'jordan - Health_11_b.xlsx',
 'jordan - Health_12.xlsx',
 'jordan - Health_13.xlsx',
 'jordan - Health_14.xlsx',
 'jordan - Health_15.xlsx',
 'jordan - Health_16.xlsx',
 'jordan - Health_17.xlsx',
 'jordan - Health_18.xlsx',
 'jordan - Health_19.xlsx',
 'jordan - Health_1_a.xlsx',
 'jordan - Health_1_b.xlsx',
 'jordan - Health_2_a.xlsx',
 'jordan - Health_2_b.xlsx',
 'jordan - Health_3_a.xlsx',
 'jordan - Health_3_b.xlsx',
 'jordan - Health_4_a.xlsx',
 'jordan - Health_4_b.xlsx',
 'jordan - Health_4_c.xlsx',
 'jordan - Health_4_d.xlsx',
 'jordan - Health_4_e.xlsx',
 'jordan - Health_4_f.xlsx',
 'jordan - Health_5_a.xlsx',
 'jordan - Health_5_b.xlsx',
 'jordan - Health_5_c.xlsx',
 'jordan - Health_5_d.xlsx',
 'jordan - Health_5_e.xlsx',
 'jordan - Health_6.xlsx',
 'jordan - Health_7.xlsx',
 'jordan - Health_8.xlsx',
 'jordan - Health_9.xlsx',
 'kuwait - Health_10.xlsx',
 'kuwait - Health_11_a.xlsx',
 'kuwait - Health_11_b.xlsx',
 'kuwait - Health_12.xlsx',
 'kuwait - Health_13.xlsx',
 'kuwait - Health_14.xlsx',
 'kuwait - Health_15.xlsx',
 'kuwait - Health_16.xlsx',
 'kuwait - Health_17.xlsx',
 'kuwait - Health_18.xlsx',
 'kuwait - Health_19.xlsx',
 'kuwait - Health_1_a.xlsx',
 'kuwait - Health_1_b.xlsx',
 'kuwait - Health_2_a.xlsx',
 'kuwait - Health_2_b.xlsx',
 'kuwait - Health_3_a.xlsx',
 'kuwait - Health_3_b.xlsx',
 'kuwait - Health_4_a.xlsx',
 'kuwait - Health_4_b.xlsx',
 'kuwait - Health_4_c.xlsx',
 'kuwait - Health_4_d.xlsx',
 'kuwait - Health_4_e.xlsx',
 'kuwait - Health_4_f.xlsx',
 'kuwait - Health_5_a.xlsx',
 'kuwait - Health_5_b.xlsx',
 'kuwait - Health_5_c.xlsx',
 'kuwait - Health_5_d.xlsx',
 'kuwait - Health_5_e.xlsx',
 'kuwait - Health_6.xlsx',
 'kuwait - Health_7.xlsx',
 'kuwait - Health_8.xlsx',
 'kuwait - Health_9.xlsx',
 'lebanon - Health_10.xlsx',
 'lebanon - Health_11_a.xlsx',
 'lebanon - Health_11_b.xlsx',
 'lebanon - Health_12.xlsx',
 'lebanon - Health_13.xlsx',
 'lebanon - Health_14.xlsx',
 'lebanon - Health_15.xlsx',
 'lebanon - Health_16.xlsx',
 'lebanon - Health_17.xlsx',
 'lebanon - Health_18.xlsx',
 'lebanon - Health_19.xlsx',
 'lebanon - Health_1_a.xlsx',
 'lebanon - Health_1_b.xlsx',
 'lebanon - Health_2_a.xlsx',
 'lebanon - Health_2_b.xlsx',
 'lebanon - Health_3_a.xlsx',
 'lebanon - Health_3_b.xlsx',
 'lebanon - Health_4_a.xlsx',
 'lebanon - Health_4_b.xlsx',
 'lebanon - Health_4_c.xlsx',
 'lebanon - Health_4_d.xlsx',
 'lebanon - Health_4_e.xlsx',
 'lebanon - Health_4_f.xlsx',
 'lebanon - Health_5_a.xlsx',
 'lebanon - Health_5_b.xlsx',
 'lebanon - Health_5_c.xlsx',
 'lebanon - Health_5_d.xlsx',
 'lebanon - Health_5_e.xlsx',
 'lebanon - Health_6.xlsx',
 'lebanon - Health_7.xlsx',
 'lebanon - Health_8.xlsx',
 'lebanon - Health_9.xlsx',
 'libya - Health_10.xlsx',
 'libya - Health_11_a.xlsx',
 'libya - Health_11_b.xlsx',
 'libya - Health_12.xlsx',
 'libya - Health_13.xlsx',
 'libya - Health_14.xlsx',
 'libya - Health_15.xlsx',
 'libya - Health_16.xlsx',
 'libya - Health_17.xlsx',
 'libya - Health_18.xlsx',
 'libya - Health_19.xlsx',
 'libya - Health_1_a.xlsx',
 'libya - Health_1_b.xlsx',
 'libya - Health_2_a.xlsx',
 'libya - Health_2_b.xlsx',
 'libya - Health_3_a.xlsx',
 'libya - Health_3_b.xlsx',
 'libya - Health_4_a.xlsx',
 'libya - Health_4_b.xlsx',
 'libya - Health_4_c.xlsx',
 'libya - Health_4_d.xlsx',
 'libya - Health_4_e.xlsx',
 'libya - Health_4_f.xlsx',
 'libya - Health_5_a.xlsx',
 'libya - Health_5_b.xlsx',
 'libya - Health_5_c.xlsx',
 'libya - Health_5_d.xlsx',
 'libya - Health_5_e.xlsx',
 'libya - Health_6.xlsx',
 'libya - Health_7.xlsx',
 'libya - Health_8.xlsx',
 'libya - Health_9.xlsx',
 'mauritania - Health_10.xlsx',
 'mauritania - Health_11_a.xlsx',
 'mauritania - Health_11_b.xlsx',
 'mauritania - Health_12.xlsx',
 'mauritania - Health_13.xlsx',
 'mauritania - Health_14.xlsx',
 'mauritania - Health_15.xlsx',
 'mauritania - Health_16.xlsx',
 'mauritania - Health_17.xlsx',
 'mauritania - Health_18.xlsx',
 'mauritania - Health_19.xlsx',
 'mauritania - Health_1_a.xlsx',
 'mauritania - Health_1_b.xlsx',
 'mauritania - Health_2_a.xlsx',
 'mauritania - Health_2_b.xlsx',
 'mauritania - Health_3_a.xlsx',
 'mauritania - Health_3_b.xlsx',
 'mauritania - Health_4_a.xlsx',
 'mauritania - Health_4_b.xlsx',
 'mauritania - Health_4_c.xlsx',
 'mauritania - Health_4_d.xlsx',
 'mauritania - Health_4_e.xlsx',
 'mauritania - Health_4_f.xlsx',
 'mauritania - Health_5_a.xlsx',
 'mauritania - Health_5_b.xlsx',
 'mauritania - Health_5_c.xlsx',
 'mauritania - Health_5_d.xlsx',
 'mauritania - Health_5_e.xlsx',
 'mauritania - Health_6.xlsx',
 'mauritania - Health_7.xlsx',
 'mauritania - Health_8.xlsx',
 'mauritania - Health_9.xlsx',
 'morocco - Health_10.xlsx',
 'morocco - Health_11_a.xlsx',
 'morocco - Health_11_b.xlsx',
 'morocco - Health_12.xlsx',
 'morocco - Health_13.xlsx',
 'morocco - Health_14.xlsx',
 'morocco - Health_15.xlsx',
 'morocco - Health_16.xlsx',
 'morocco - Health_17.xlsx',
 'morocco - Health_18.xlsx',
 'morocco - Health_19.xlsx',
 'morocco - Health_1_a.xlsx',
 'morocco - Health_1_b.xlsx',
 'morocco - Health_2_a.xlsx',
 'morocco - Health_2_b.xlsx',
 'morocco - Health_3_a.xlsx',
 'morocco - Health_3_b.xlsx',
 'morocco - Health_4_a.xlsx',
 'morocco - Health_4_b.xlsx',
 'morocco - Health_4_c.xlsx',
 'morocco - Health_4_d.xlsx',
 'morocco - Health_4_e.xlsx',
 'morocco - Health_4_f.xlsx',
 'morocco - Health_5_a.xlsx',
 'morocco - Health_5_b.xlsx',
 'morocco - Health_5_c.xlsx',
 'morocco - Health_5_d.xlsx',
 'morocco - Health_5_e.xlsx',
 'morocco - Health_6.xlsx',
 'morocco - Health_7.xlsx',
 'morocco - Health_8.xlsx',
 'morocco - Health_9.xlsx',
 'oman - Health_10.xlsx',
 'oman - Health_11_a.xlsx',
 'oman - Health_11_b.xlsx',
 'oman - Health_12.xlsx',
 'oman - Health_13.xlsx',
 'oman - Health_14.xlsx',
 'oman - Health_15.xlsx',
 'oman - Health_16.xlsx',
 'oman - Health_17.xlsx',
 'oman - Health_18.xlsx',
 'oman - Health_19.xlsx',
 'oman - Health_1_a.xlsx',
 'oman - Health_1_b.xlsx',
 'oman - Health_2_a.xlsx',
 'oman - Health_2_b.xlsx',
 'oman - Health_3_a.xlsx',
 'oman - Health_3_b.xlsx',
 'oman - Health_4_a.xlsx',
 'oman - Health_4_b.xlsx',
 'oman - Health_4_c.xlsx',
 'oman - Health_4_d.xlsx',
 'oman - Health_4_e.xlsx',
 'oman - Health_4_f.xlsx',
 'oman - Health_5_a.xlsx',
 'oman - Health_5_b.xlsx',
 'oman - Health_5_c.xlsx',
 'oman - Health_5_d.xlsx',
 'oman - Health_5_e.xlsx',
 'oman - Health_6.xlsx',
 'oman - Health_7.xlsx',
 'oman - Health_8.xlsx',
 'oman - Health_9.xlsx',
 'palestine - Health_10.xlsx',
 'palestine - Health_11_a.xlsx',
 'palestine - Health_11_b.xlsx',
 'palestine - Health_12.xlsx',
 'palestine - Health_13.xlsx',
 'palestine - Health_14.xlsx',
 'palestine - Health_15.xlsx',
 'palestine - Health_16.xlsx',
 'palestine - Health_17.xlsx',
 'palestine - Health_18.xlsx',
 'palestine - Health_19.xlsx',
 'palestine - Health_1_a.xlsx',
 'palestine - Health_1_b.xlsx',
 'palestine - Health_2_a.xlsx',
 'palestine - Health_2_b.xlsx',
 'palestine - Health_3_a.xlsx',
 'palestine - Health_3_b.xlsx',
 'palestine - Health_4_a.xlsx',
 'palestine - Health_4_b.xlsx',
 'palestine - Health_4_c.xlsx',
 'palestine - Health_4_d.xlsx',
 'palestine - Health_4_e.xlsx',
 'palestine - Health_4_f.xlsx',
 'palestine - Health_5_a.xlsx',
 'palestine - Health_5_b.xlsx',
 'palestine - Health_5_c.xlsx',
 'palestine - Health_5_d.xlsx',
 'palestine - Health_5_e.xlsx',
 'palestine - Health_6.xlsx',
 'palestine - Health_7.xlsx',
 'palestine - Health_8.xlsx',
 'palestine - Health_9.xlsx',
 'qatar - Health_10.xlsx',
 'qatar - Health_11_a.xlsx',
 'qatar - Health_11_b.xlsx',
 'qatar - Health_12.xlsx',
 'qatar - Health_13.xlsx',
 'qatar - Health_14.xlsx',
 'qatar - Health_15.xlsx',
 'qatar - Health_16.xlsx',
 'qatar - Health_17.xlsx',
 'qatar - Health_18.xlsx',
 'qatar - Health_19.xlsx',
 'qatar - Health_1_a.xlsx',
 'qatar - Health_1_b.xlsx',
 'qatar - Health_2_a.xlsx',
 'qatar - Health_2_b.xlsx',
 'qatar - Health_3_a.xlsx',
 'qatar - Health_3_b.xlsx',
 'qatar - Health_4_a.xlsx',
 'qatar - Health_4_b.xlsx',
 'qatar - Health_4_c.xlsx',
 'qatar - Health_4_d.xlsx',
 'qatar - Health_4_e.xlsx',
 'qatar - Health_4_f.xlsx',
 'qatar - Health_5_a.xlsx',
 'qatar - Health_5_b.xlsx',
 'qatar - Health_5_c.xlsx',
 'qatar - Health_5_d.xlsx',
 'qatar - Health_5_e.xlsx',
 'qatar - Health_6.xlsx',
 'qatar - Health_7.xlsx',
 'qatar - Health_8.xlsx',
 'qatar - Health_9.xlsx',
 'saudi - Health_10.xlsx',
 'saudi - Health_11_a.xlsx',
 'saudi - Health_11_b.xlsx',
 'saudi - Health_12.xlsx',
 'saudi - Health_13.xlsx',
 'saudi - Health_14.xlsx',
 'saudi - Health_15.xlsx',
 'saudi - Health_16.xlsx',
 'saudi - Health_17.xlsx',
 'saudi - Health_18.xlsx',
 'saudi - Health_19.xlsx',
 'saudi - Health_1_a.xlsx',
 'saudi - Health_1_b.xlsx',
 'saudi - Health_2_a.xlsx',
 'saudi - Health_2_b.xlsx',
 'saudi - Health_3_a.xlsx',
 'saudi - Health_3_b.xlsx',
 'saudi - Health_4_a.xlsx',
 'saudi - Health_4_b.xlsx',
 'saudi - Health_4_c.xlsx',
 'saudi - Health_4_d.xlsx',
 'saudi - Health_4_e.xlsx',
 'saudi - Health_4_f.xlsx',
 'saudi - Health_5_a.xlsx',
 'saudi - Health_5_b.xlsx',
 'saudi - Health_5_c.xlsx',
 'saudi - Health_5_d.xlsx',
 'saudi - Health_5_e.xlsx',
 'saudi - Health_6.xlsx',
 'saudi - Health_7.xlsx',
 'saudi - Health_8.xlsx',
 'saudi - Health_9.xlsx',
 'somalia - Health_10.xlsx',
 'somalia - Health_11_a.xlsx',
 'somalia - Health_11_b.xlsx',
 'somalia - Health_12.xlsx',
 'somalia - Health_13.xlsx',
 'somalia - Health_14.xlsx',
 'somalia - Health_15.xlsx',
 'somalia - Health_16.xlsx',
 'somalia - Health_17.xlsx',
 'somalia - Health_18.xlsx',
 'somalia - Health_19.xlsx',
 'somalia - Health_1_a.xlsx',
 'somalia - Health_1_b.xlsx',
 'somalia - Health_2_a.xlsx',
 'somalia - Health_2_b.xlsx',
 'somalia - Health_3_a.xlsx',
 'somalia - Health_3_b.xlsx',
 'somalia - Health_4_a.xlsx',
 'somalia - Health_4_b.xlsx',
 'somalia - Health_4_c.xlsx',
 'somalia - Health_4_d.xlsx',
 'somalia - Health_4_e.xlsx',
 'somalia - Health_4_f.xlsx',
 'somalia - Health_5_a.xlsx',
 'somalia - Health_5_b.xlsx',
 'somalia - Health_5_c.xlsx',
 'somalia - Health_5_d.xlsx',
 'somalia - Health_5_e.xlsx',
 'somalia - Health_6.xlsx',
 'somalia - Health_7.xlsx',
 'somalia - Health_8.xlsx',
 'somalia - Health_9.xlsx',
 'sudan - Health_10.xlsx',
 'sudan - Health_11_a.xlsx',
 'sudan - Health_11_b.xlsx',
 'sudan - Health_12.xlsx',
 'sudan - Health_13.xlsx',
 'sudan - Health_14.xlsx',
 'sudan - Health_15.xlsx',
 'sudan - Health_16.xlsx',
 'sudan - Health_17.xlsx',
 'sudan - Health_18.xlsx',
 'sudan - Health_19.xlsx',
 'sudan - Health_1_a.xlsx',
 'sudan - Health_1_b.xlsx',
 'sudan - Health_2_a.xlsx',
 'sudan - Health_2_b.xlsx',
 'sudan - Health_3_a.xlsx',
 'sudan - Health_3_b.xlsx',
 'sudan - Health_4_a.xlsx',
 'sudan - Health_4_b.xlsx',
 'sudan - Health_4_c.xlsx',
 'sudan - Health_4_d.xlsx',
 'sudan - Health_4_e.xlsx',
 'sudan - Health_4_f.xlsx',
 'sudan - Health_5_a.xlsx',
 'sudan - Health_5_b.xlsx',
 'sudan - Health_5_c.xlsx',
 'sudan - Health_5_d.xlsx',
 'sudan - Health_5_e.xlsx',
 'sudan - Health_6.xlsx',
 'sudan - Health_7.xlsx',
 'sudan - Health_8.xlsx',
 'sudan - Health_9.xlsx',
 'syria - Health_10.xlsx',
 'syria - Health_11_a.xlsx',
 'syria - Health_11_b.xlsx',
 'syria - Health_12.xlsx',
 'syria - Health_13.xlsx',
 'syria - Health_14.xlsx',
 'syria - Health_15.xlsx',
 'syria - Health_16.xlsx',
 'syria - Health_17.xlsx',
 'syria - Health_18.xlsx',
 'syria - Health_19.xlsx',
 'syria - Health_1_a.xlsx',
 'syria - Health_1_b.xlsx',
 'syria - Health_2_a.xlsx',
 'syria - Health_2_b.xlsx',
 'syria - Health_3_a.xlsx',
 'syria - Health_3_b.xlsx',
 'syria - Health_4_a.xlsx',
 'syria - Health_4_b.xlsx',
 'syria - Health_4_c.xlsx',
 'syria - Health_4_d.xlsx',
 'syria - Health_4_e.xlsx',
 'syria - Health_4_f.xlsx',
 'syria - Health_5_a.xlsx',
 'syria - Health_5_b.xlsx',
 'syria - Health_5_c.xlsx',
 'syria - Health_5_d.xlsx',
 'syria - Health_5_e.xlsx',
 'syria - Health_6.xlsx',
 'syria - Health_7.xlsx',
 'syria - Health_8.xlsx',
 'syria - Health_9.xlsx',
 'tunisia - Health_10.xlsx',
 'tunisia - Health_11_a.xlsx',
 'tunisia - Health_11_b.xlsx',
 'tunisia - Health_12.xlsx',
 'tunisia - Health_13.xlsx',
 'tunisia - Health_14.xlsx',
 'tunisia - Health_15.xlsx',
 'tunisia - Health_16.xlsx',
 'tunisia - Health_17.xlsx',
 'tunisia - Health_18.xlsx',
 'tunisia - Health_19.xlsx',
 'tunisia - Health_1_a.xlsx',
 'tunisia - Health_1_b.xlsx',
 'tunisia - Health_2_a.xlsx',
 'tunisia - Health_2_b.xlsx',
 'tunisia - Health_3_a.xlsx',
 'tunisia - Health_3_b.xlsx',
 'tunisia - Health_4_a.xlsx',
 'tunisia - Health_4_b.xlsx',
 'tunisia - Health_4_c.xlsx',
 'tunisia - Health_4_d.xlsx',
 'tunisia - Health_4_e.xlsx',
 'tunisia - Health_4_f.xlsx',
 'tunisia - Health_5_a.xlsx',
 'tunisia - Health_5_b.xlsx',
 'tunisia - Health_5_c.xlsx',
 'tunisia - Health_5_d.xlsx',
 'tunisia - Health_5_e.xlsx',
 'tunisia - Health_6.xlsx',
 'tunisia - Health_7.xlsx',
 'tunisia - Health_8.xlsx',
 'tunisia - Health_9.xlsx',
 'uae - Health_10.xlsx',
 'uae - Health_11_a.xlsx',
 'uae - Health_11_b.xlsx',
 'uae - Health_12.xlsx',
 'uae - Health_13.xlsx',
 'uae - Health_14.xlsx',
 'uae - Health_15.xlsx',
 'uae - Health_16.xlsx',
 'uae - Health_17.xlsx',
 'uae - Health_18.xlsx',
 'uae - Health_19.xlsx',
 'uae - Health_1_a.xlsx',
 'uae - Health_1_b.xlsx',
 'uae - Health_2_a.xlsx',
 'uae - Health_2_b.xlsx',
 'uae - Health_3_a.xlsx',
 'uae - Health_3_b.xlsx',
 'uae - Health_4_a.xlsx',
 'uae - Health_4_b.xlsx',
 'uae - Health_4_c.xlsx',
 'uae - Health_4_d.xlsx',
 'uae - Health_4_e.xlsx',
 'uae - Health_4_f.xlsx',
 'uae - Health_5_a.xlsx',
 'uae - Health_5_b.xlsx',
 'uae - Health_5_c.xlsx',
 'uae - Health_5_d.xlsx',
 'uae - Health_5_e.xlsx',
 'uae - Health_6.xlsx',
 'uae - Health_7.xlsx',
 'uae - Health_8.xlsx',
 'uae - Health_9.xlsx',
 'yemen - Health_10.xlsx',
 'yemen - Health_11_a.xlsx',
 'yemen - Health_11_b.xlsx',
 'yemen - Health_12.xlsx',
 'yemen - Health_13.xlsx',
 'yemen - Health_14.xlsx',
 'yemen - Health_15.xlsx',
 'yemen - Health_16.xlsx',
 'yemen - Health_17.xlsx',
 'yemen - Health_18.xlsx',
 'yemen - Health_19.xlsx',
 'yemen - Health_1_a.xlsx',
 'yemen - Health_1_b.xlsx',
 'yemen - Health_2_a.xlsx',
 'yemen - Health_2_b.xlsx',
 'yemen - Health_3_a.xlsx',
 'yemen - Health_3_b.xlsx',
 'yemen - Health_4_a.xlsx',
 'yemen - Health_4_b.xlsx',
 'yemen - Health_4_c.xlsx',
 'yemen - Health_4_d.xlsx',
 'yemen - Health_4_e.xlsx',
 'yemen - Health_4_f.xlsx',
 'yemen - Health_5_a.xlsx',
 'yemen - Health_5_b.xlsx',
 'yemen - Health_5_c.xlsx',

In [ ]:
#read in all files and combine into a single dataframe
dataframes = []

for file in xlsx_files:
    print(f'processing {file} file')
    df_raw = pd.read_excel(os.path.join(folder_path, file), header=None, dtype=str)

    #Find the row nums where col zero has words "index"
    header_rows = df_raw.index[df_raw[0] == 'index'].tolist()

    # Get the value of these rows to be used as headers
    header_1_values = df_raw.iloc[header_rows[0]].dropna()
    header_2_values = df_raw.iloc[header_rows[1]].dropna()


    # for dataframe containing data: slice dataframe 1 (index=1) and set header
    df_data = df_raw[df_raw[0] == '1'].copy()
    # Set the columns using the 1st header we found
    df_data.columns = header_1_values
    #reshape the data dataframe from wide to long
    #id_vars are all colums that are not integers (years)
    id_variables = [col for col in header_1_values if not col.isdigit()]

    df_data=df_data.melt(id_vars=id_variables, var_name='السنة', value_name='العدد')
    df_data.drop(columns=['index'], inplace=True)


    # for the source dataframe
    df_source = df_raw[df_raw[0] == '2'].copy()
    # drop all the empty columns on the right side immediately.
    df_source = df_source[header_2_values.index]
    # Set the columns using the 2nd header we found
    df_source.columns = header_2_values
    df_source.drop(columns=['index'], inplace=True)

    #merge the source with the data left on المؤشر, السنة
    df_merged=pd.merge(df_data, df_source, on=['السنة','المؤشر', 'الدولة'], how='left')
    dataframes.append(df_merged)


# Combine all
final_df = pd.concat(dataframes, ignore_index=True)

# Drop columns where ALL values are missing (NaN)
final_df = final_df.dropna(axis=1, how='all')

#save to excel
final_df.to_excel('final_dataset.xlsx', index=False)

# Generate the dictionary (excluding specified columns)
exclude_cols=['السنة', 'العدد', ]
unique_values_dict = {
    col: sorted(final_df[col].dropna().unique().tolist()) 
    for col in final_df.columns if col not in exclude_cols
}

processing algeria - Health_10.xlsx file
processing algeria - Health_11_a.xlsx file
processing algeria - Health_11_b.xlsx file
processing algeria - Health_12.xlsx file
processing algeria - Health_13.xlsx file
processing algeria - Health_14.xlsx file
processing algeria - Health_15.xlsx file
processing algeria - Health_16.xlsx file
processing algeria - Health_17.xlsx file
processing algeria - Health_18.xlsx file
processing algeria - Health_19.xlsx file
processing algeria - Health_1_a.xlsx file
processing algeria - Health_1_b.xlsx file
processing algeria - Health_2_a.xlsx file
processing algeria - Health_2_b.xlsx file
processing algeria - Health_3_a.xlsx file
processing algeria - Health_3_b.xlsx file
processing algeria - Health_4_a.xlsx file
processing algeria - Health_4_b.xlsx file
processing algeria - Health_4_c.xlsx file
processing algeria - Health_4_d.xlsx file
processing algeria - Health_4_e.xlsx file
processing algeria - Health_4_f.xlsx file
processing algeria - Health_5_a.xlsx file
processing algeria - Health_5_b.xlsx file
processing algeria - Health_5_c.xlsx file
processing algeria - Health_5_d.xlsx file
processing algeria - Health_5_e.xlsx file
processing algeria - Health_6.xlsx file
processing algeria - Health_7.xlsx file
processing algeria - Health_8.xlsx file
processing algeria - Health_9.xlsx file
processing bahrain - Health_10.xlsx file
processing bahrain - Health_11_a.xlsx file
processing bahrain - Health_11_b.xlsx file
processing bahrain - Health_12.xlsx file
processing bahrain - Health_13.xlsx file
processing bahrain - Health_14.xlsx file
processing bahrain - Health_15.xlsx file
processing bahrain - Health_16.xlsx file
processing bahrain - Health_17.xlsx file
processing bahrain - Health_18.xlsx file
processing bahrain - Health_19.xlsx file
processing bahrain - Health_1_a.xlsx file
processing bahrain - Health_1_b.xlsx file
processing bahrain - Health_2_a.xlsx file
processing bahrain - Health_2_b.xlsx file
processing bahrain - Health_3_a.xlsx file
processing bahrain - Health_3_b.xlsx file
processing bahrain - Health_4_a.xlsx file
processing bahrain - Health_4_b.xlsx file
processing bahrain - Health_4_c.xlsx file
processing bahrain - Health_4_d.xlsx file
processing bahrain - Health_4_e.xlsx file
processing bahrain - Health_4_f.xlsx file
processing bahrain - Health_5_a.xlsx file
processing bahrain - Health_5_b.xlsx file
processing bahrain - Health_5_c.xlsx file
processing bahrain - Health_5_d.xlsx file
processing bahrain - Health_5_e.xlsx file
processing bahrain - Health_6.xlsx file
processing bahrain - Health_7.xlsx file
processing bahrain - Health_8.xlsx file
processing bahrain - Health_9.xlsx file
processing comoros - Health_10.xlsx file
processing comoros - Health_11_a.xlsx file
processing comoros - Health_11_b.xlsx file
processing comoros - Health_12.xlsx file
processing comoros - Health_13.xlsx file
processing comoros - Health_14.xlsx file
processing comoros - Health_15.xlsx file
processing comoros - Health_16.xlsx file
processing comoros - Health_17.xlsx file
processing comoros - Health_18.xlsx file
processing comoros - Health_19.xlsx file
processing comoros - Health_1_a.xlsx file
processing comoros - Health_1_b.xlsx file
processing comoros - Health_2_a.xlsx file
processing comoros - Health_2_b.xlsx file
processing comoros - Health_3_a.xlsx file
processing comoros - Health_3_b.xlsx file
processing comoros - Health_4_a.xlsx file
processing comoros - Health_4_b.xlsx file
processing comoros - Health_4_c.xlsx file
processing comoros - Health_4_d.xlsx file
processing comoros - Health_4_e.xlsx file
processing comoros - Health_4_f.xlsx file
processing comoros - Health_5_a.xlsx file
processing comoros - Health_5_b.xlsx file
processing comoros - Health_5_c.xlsx file
processing comoros - Health_5_d.xlsx file
processing comoros - Health_5_e.xlsx file
processing comoros - Health_6.xlsx file
processing comoros - Health_7.xlsx file
processing comoros - Health_8.xlsx file
processing comoros - Health_9.xlsx file
processing djibouti - Health_10.xlsx file
processing djibouti - Health_11_a.xlsx file
processing djibouti - Health_11_b.xlsx file
processing djibouti - Health_12.xlsx file
processing djibouti - Health_13.xlsx file
processing djibouti - Health_14.xlsx file
processing djibouti - Health_15.xlsx file
processing djibouti - Health_16.xlsx file
processing djibouti - Health_17.xlsx file
processing djibouti - Health_18.xlsx file
processing djibouti - Health_19.xlsx file
processing djibouti - Health_1_a.xlsx file
processing djibouti - Health_1_b.xlsx file
processing djibouti - Health_2_a.xlsx file
processing djibouti - Health_2_b.xlsx file
processing djibouti - Health_3_a.xlsx file
processing djibouti - Health_3_b.xlsx file
processing djibouti - Health_4_a.xlsx file
processing djibouti - Health_4_b.xlsx file
processing djibouti - Health_4_c.xlsx file
processing djibouti - Health_4_d.xlsx file
processing djibouti - Health_4_e.xlsx file
processing djibouti - Health_4_f.xlsx file
processing djibouti - Health_5_a.xlsx file
processing djibouti - Health_5_b.xlsx file
processing djibouti - Health_5_c.xlsx file
processing djibouti - Health_5_d.xlsx file
processing djibouti - Health_5_e.xlsx file
processing djibouti - Health_6.xlsx file
processing djibouti - Health_7.xlsx file
processing djibouti - Health_8.xlsx file
processing djibouti - Health_9.xlsx file
processing egypt - Health_10.xlsx file
processing egypt - Health_11_a.xlsx file
processing egypt - Health_11_b.xlsx file
processing egypt - Health_12.xlsx file
processing egypt - Health_13.xlsx file
processing egypt - Health_14.xlsx file
processing egypt - Health_15.xlsx file
processing egypt - Health_16.xlsx file
processing egypt - Health_17.xlsx file
processing egypt - Health_18.xlsx file
processing egypt - Health_19.xlsx file
processing egypt - Health_1_a.xlsx file
processing egypt - Health_1_b.xlsx file
processing egypt - Health_2_a.xlsx file
processing egypt - Health_2_b.xlsx file
processing egypt - Health_3_a.xlsx file
processing egypt - Health_3_b.xlsx file
processing egypt - Health_4_a.xlsx file
processing egypt - Health_4_b.xlsx file
processing egypt - Health_4_c.xlsx file
processing egypt - Health_4_d.xlsx file
processing egypt - Health_4_e.xlsx file
processing egypt - Health_4_f.xlsx file
processing egypt - Health_5_a.xlsx file
processing egypt - Health_5_b.xlsx file
processing egypt - Health_5_c.xlsx file
processing egypt - Health_5_d.xlsx file
processing egypt - Health_5_e.xlsx file
processing egypt - Health_6.xlsx file
processing egypt - Health_7.xlsx file
processing egypt - Health_8.xlsx file
processing egypt - Health_9.xlsx file
processing iraq - Health_10.xlsx file
processing iraq - Health_11_a.xlsx file
processing iraq - Health_11_b.xlsx file
processing iraq - Health_12.xlsx file
processing iraq - Health_13.xlsx file
processing iraq - Health_14.xlsx file
processing iraq - Health_15.xlsx file
processing iraq - Health_16.xlsx file
processing iraq - Health_17.xlsx file
processing iraq - Health_18.xlsx file
processing iraq - Health_19.xlsx file
processing iraq - Health_1_a.xlsx file
processing iraq - Health_1_b.xlsx file
processing iraq - Health_2_a.xlsx file
processing iraq - Health_2_b.xlsx file
processing iraq - Health_3_a.xlsx file
processing iraq - Health_3_b.xlsx file
processing iraq - Health_4_a.xlsx file
processing iraq - Health_4_b.xlsx file
processing iraq - Health_4_c.xlsx file
processing iraq - Health_4_d.xlsx file
processing iraq - Health_4_e.xlsx file
processing iraq - Health_4_f.xlsx file
processing iraq - Health_5_a.xlsx file
processing iraq - Health_5_b.xlsx file
processing iraq - Health_5_c.xlsx file
processing iraq - Health_5_d.xlsx file
processing iraq - Health_5_e.xlsx file
processing iraq - Health_6.xlsx file
processing iraq - Health_7.xlsx file
processing iraq - Health_8.xlsx file
processing iraq - Health_9.xlsx file
processing jordan - Health_10.xlsx file
processing jordan - Health_11_a.xlsx file
processing jordan - Health_11_b.xlsx file
processing jordan - Health_12.xlsx file
processing jordan - Health_13.xlsx file
processing jordan - Health_14.xlsx file
processing jordan - Health_15.xlsx file
processing jordan - Health_16.xlsx file
processing jordan - Health_17.xlsx file
processing jordan - Health_18.xlsx file
processing jordan - Health_19.xlsx file
processing jordan - Health_1_a.xlsx file
processing jordan - Health_1_b.xlsx file
processing jordan - Health_2_a.xlsx file
processing jordan - Health_2_b.xlsx file
processing jordan - Health_3_a.xlsx file
processing jordan - Health_3_b.xlsx file
processing jordan - Health_4_a.xlsx file
processing jordan - Health_4_b.xlsx file
processing jordan - Health_4_c.xlsx file
processing jordan - Health_4_d.xlsx file
processing jordan - Health_4_e.xlsx file
processing jordan - Health_4_f.xlsx file
processing jordan - Health_5_a.xlsx file
processing jordan - Health_5_b.xlsx file
processing jordan - Health_5_c.xlsx file
processing jordan - Health_5_d.xlsx file
processing jordan - Health_5_e.xlsx file
processing jordan - Health_6.xlsx file
processing jordan - Health_7.xlsx file
processing jordan - Health_8.xlsx file
processing jordan - Health_9.xlsx file
processing kuwait - Health_10.xlsx file
processing kuwait - Health_11_a.xlsx file
processing kuwait - Health_11_b.xlsx file
processing kuwait - Health_12.xlsx file
processing kuwait - Health_13.xlsx file
processing kuwait - Health_14.xlsx file
processing kuwait - Health_15.xlsx file
processing kuwait - Health_16.xlsx file
processing kuwait - Health_17.xlsx file
processing kuwait - Health_18.xlsx file
processing kuwait - Health_19.xlsx file
processing kuwait - Health_1_a.xlsx file
processing kuwait - Health_1_b.xlsx file
processing kuwait - Health_2_a.xlsx file
processing kuwait - Health_2_b.xlsx file
processing kuwait - Health_3_a.xlsx file
processing kuwait - Health_3_b.xlsx file
processing kuwait - Health_4_a.xlsx file
processing kuwait - Health_4_b.xlsx file
processing kuwait - Health_4_c.xlsx file
processing kuwait - Health_4_d.xlsx file
processing kuwait - Health_4_e.xlsx file
processing kuwait - Health_4_f.xlsx file
processing kuwait - Health_5_a.xlsx file
processing kuwait - Health_5_b.xlsx file
processing kuwait - Health_5_c.xlsx file
processing kuwait - Health_5_d.xlsx file
processing kuwait - Health_5_e.xlsx file
processing kuwait - Health_6.xlsx file
processing kuwait - Health_7.xlsx file
processing kuwait - Health_8.xlsx file
processing kuwait - Health_9.xlsx file
processing lebanon - Health_10.xlsx file
processing lebanon - Health_11_a.xlsx file
processing lebanon - Health_11_b.xlsx file
processing lebanon - Health_12.xlsx file
processing lebanon - Health_13.xlsx file
processing lebanon - Health_14.xlsx file
processing lebanon - Health_15.xlsx file
processing lebanon - Health_16.xlsx file
processing lebanon - Health_17.xlsx file
processing lebanon - Health_18.xlsx file
processing lebanon - Health_19.xlsx file
processing lebanon - Health_1_a.xlsx file
processing lebanon - Health_1_b.xlsx file
processing lebanon - Health_2_a.xlsx file
processing lebanon - Health_2_b.xlsx file
processing lebanon - Health_3_a.xlsx file
processing lebanon - Health_3_b.xlsx file
processing lebanon - Health_4_a.xlsx file
processing lebanon - Health_4_b.xlsx file
processing lebanon - Health_4_c.xlsx file
processing lebanon - Health_4_d.xlsx file
processing lebanon - Health_4_e.xlsx file
processing lebanon - Health_4_f.xlsx file
processing lebanon - Health_5_a.xlsx file
processing lebanon - Health_5_b.xlsx file
processing lebanon - Health_5_c.xlsx file
processing lebanon - Health_5_d.xlsx file
processing lebanon - Health_5_e.xlsx file
processing lebanon - Health_6.xlsx file
processing lebanon - Health_7.xlsx file
processing lebanon - Health_8.xlsx file
processing lebanon - Health_9.xlsx file
processing libya - Health_10.xlsx file
processing libya - Health_11_a.xlsx file
processing libya - Health_11_b.xlsx file
processing libya - Health_12.xlsx file
processing libya - Health_13.xlsx file
processing libya - Health_14.xlsx file
processing libya - Health_15.xlsx file
processing libya - Health_16.xlsx file
processing libya - Health_17.xlsx file
processing libya - Health_18.xlsx file
processing libya - Health_19.xlsx file
processing libya - Health_1_a.xlsx file
processing libya - Health_1_b.xlsx file
processing libya - Health_2_a.xlsx file
processing libya - Health_2_b.xlsx file
processing libya - Health_3_a.xlsx file
processing libya - Health_3_b.xlsx file
processing libya - Health_4_a.xlsx file
processing libya - Health_4_b.xlsx file
processing libya - Health_4_c.xlsx file
processing libya - Health_4_d.xlsx file
processing libya - Health_4_e.xlsx file
processing libya - Health_4_f.xlsx file
processing libya - Health_5_a.xlsx file
processing libya - Health_5_b.xlsx file
processing libya - Health_5_c.xlsx file
processing libya - Health_5_d.xlsx file
processing libya - Health_5_e.xlsx file
processing libya - Health_6.xlsx file
processing libya - Health_7.xlsx file
processing libya - Health_8.xlsx file
processing libya - Health_9.xlsx file
processing mauritania - Health_10.xlsx file
processing mauritania - Health_11_a.xlsx file
processing mauritania - Health_11_b.xlsx file
processing mauritania - Health_12.xlsx file
processing mauritania - Health_13.xlsx file
processing mauritania - Health_14.xlsx file
processing mauritania - Health_15.xlsx file
processing mauritania - Health_16.xlsx file
processing mauritania - Health_17.xlsx file
processing mauritania - Health_18.xlsx file
processing mauritania - Health_19.xlsx file
processing mauritania - Health_1_a.xlsx file
processing mauritania - Health_1_b.xlsx file
processing mauritania - Health_2_a.xlsx file
processing mauritania - Health_2_b.xlsx file
processing mauritania - Health_3_a.xlsx file
processing mauritania - Health_3_b.xlsx file
processing mauritania - Health_4_a.xlsx file
processing mauritania - Health_4_b.xlsx file
processing mauritania - Health_4_c.xlsx file
processing mauritania - Health_4_d.xlsx file
processing mauritania - Health_4_e.xlsx file
processing mauritania - Health_4_f.xlsx file
processing mauritania - Health_5_a.xlsx file
processing mauritania - Health_5_b.xlsx file
processing mauritania - Health_5_c.xlsx file
processing mauritania - Health_5_d.xlsx file
processing mauritania - Health_5_e.xlsx file
processing mauritania - Health_6.xlsx file
processing mauritania - Health_7.xlsx file
processing mauritania - Health_8.xlsx file
processing mauritania - Health_9.xlsx file
processing morocco - Health_10.xlsx file
processing morocco - Health_11_a.xlsx file
processing morocco - Health_11_b.xlsx file
processing morocco - Health_12.xlsx file
processing morocco - Health_13.xlsx file
processing morocco - Health_14.xlsx file
processing morocco - Health_15.xlsx file
processing morocco - Health_16.xlsx file
processing morocco - Health_17.xlsx file
processing morocco - Health_18.xlsx file
processing morocco - Health_19.xlsx file
processing morocco - Health_1_a.xlsx file
processing morocco - Health_1_b.xlsx file
processing morocco - Health_2_a.xlsx file
processing morocco - Health_2_b.xlsx file
processing morocco - Health_3_a.xlsx file
processing morocco - Health_3_b.xlsx file
processing morocco - Health_4_a.xlsx file
processing morocco - Health_4_b.xlsx file
processing morocco - Health_4_c.xlsx file
processing morocco - Health_4_d.xlsx file
processing morocco - Health_4_e.xlsx file
processing morocco - Health_4_f.xlsx file
processing morocco - Health_5_a.xlsx file
processing morocco - Health_5_b.xlsx file
processing morocco - Health_5_c.xlsx file
processing morocco - Health_5_d.xlsx file
processing morocco - Health_5_e.xlsx file
processing morocco - Health_6.xlsx file
processing morocco - Health_7.xlsx file
processing morocco - Health_8.xlsx file
processing morocco - Health_9.xlsx file
processing oman - Health_10.xlsx file
processing oman - Health_11_a.xlsx file
processing oman - Health_11_b.xlsx file
processing oman - Health_12.xlsx file
processing oman - Health_13.xlsx file
processing oman - Health_14.xlsx file
processing oman - Health_15.xlsx file
processing oman - Health_16.xlsx file
processing oman - Health_17.xlsx file
processing oman - Health_18.xlsx file
processing oman - Health_19.xlsx file
processing oman - Health_1_a.xlsx file
processing oman - Health_1_b.xlsx file
processing oman - Health_2_a.xlsx file
processing oman - Health_2_b.xlsx file
processing oman - Health_3_a.xlsx file
processing oman - Health_3_b.xlsx file
processing oman - Health_4_a.xlsx file
processing oman - Health_4_b.xlsx file
processing oman - Health_4_c.xlsx file
processing oman - Health_4_d.xlsx file
processing oman - Health_4_e.xlsx file
processing oman - Health_4_f.xlsx file
processing oman - Health_5_a.xlsx file
processing oman - Health_5_b.xlsx file
processing oman - Health_5_c.xlsx file
processing oman - Health_5_d.xlsx file
processing oman - Health_5_e.xlsx file
processing oman - Health_6.xlsx file
processing oman - Health_7.xlsx file
processing oman - Health_8.xlsx file
processing oman - Health_9.xlsx file
processing palestine - Health_10.xlsx file
processing palestine - Health_11_a.xlsx file
processing palestine - Health_11_b.xlsx file
processing palestine - Health_12.xlsx file
processing palestine - Health_13.xlsx file
processing palestine - Health_14.xlsx file
processing palestine - Health_15.xlsx file
processing palestine - Health_16.xlsx file
processing palestine - Health_17.xlsx file
processing palestine - Health_18.xlsx file
processing palestine - Health_19.xlsx file
processing palestine - Health_1_a.xlsx file
processing palestine - Health_1_b.xlsx file
processing palestine - Health_2_a.xlsx file
processing palestine - Health_2_b.xlsx file
processing palestine - Health_3_a.xlsx file
processing palestine - Health_3_b.xlsx file
processing palestine - Health_4_a.xlsx file
processing palestine - Health_4_b.xlsx file
processing palestine - Health_4_c.xlsx file
processing palestine - Health_4_d.xlsx file
processing palestine - Health_4_e.xlsx file
processing palestine - Health_4_f.xlsx file
processing palestine - Health_5_a.xlsx file
processing palestine - Health_5_b.xlsx file
processing palestine - Health_5_c.xlsx file
processing palestine - Health_5_d.xlsx file
processing palestine - Health_5_e.xlsx file
processing palestine - Health_6.xlsx file
processing palestine - Health_7.xlsx file
processing palestine - Health_8.xlsx file
processing palestine - Health_9.xlsx file
processing qatar - Health_10.xlsx file
processing qatar - Health_11_a.xlsx file
processing qatar - Health_11_b.xlsx file
processing qatar - Health_12.xlsx file
processing qatar - Health_13.xlsx file
processing qatar - Health_14.xlsx file
processing qatar - Health_15.xlsx file
processing qatar - Health_16.xlsx file
processing qatar - Health_17.xlsx file
processing qatar - Health_18.xlsx file
processing qatar - Health_19.xlsx file
processing qatar - Health_1_a.xlsx file
processing qatar - Health_1_b.xlsx file
processing qatar - Health_2_a.xlsx file
processing qatar - Health_2_b.xlsx file
processing qatar - Health_3_a.xlsx file
processing qatar - Health_3_b.xlsx file
processing qatar - Health_4_a.xlsx file
processing qatar - Health_4_b.xlsx file
processing qatar - Health_4_c.xlsx file
processing qatar - Health_4_d.xlsx file
processing qatar - Health_4_e.xlsx file
processing qatar - Health_4_f.xlsx file
processing qatar - Health_5_a.xlsx file
processing qatar - Health_5_b.xlsx file
processing qatar - Health_5_c.xlsx file
processing qatar - Health_5_d.xlsx file
processing qatar - Health_5_e.xlsx file
processing qatar - Health_6.xlsx file
processing qatar - Health_7.xlsx file
processing qatar - Health_8.xlsx file
processing qatar - Health_9.xlsx file
processing saudi - Health_10.xlsx file
processing saudi - Health_11_a.xlsx file
processing saudi - Health_11_b.xlsx file
processing saudi - Health_12.xlsx file
processing saudi - Health_13.xlsx file
processing saudi - Health_14.xlsx file
processing saudi - Health_15.xlsx file
processing saudi - Health_16.xlsx file

In [6]:
dataframes[100]

         المؤشر  الدولة السنة العدد المصدر
0   عدد الأطباء  جيبوتي  2010   NaN    NaN
1   عدد الأطباء  جيبوتي  2011   NaN    NaN
2   عدد الأطباء  جيبوتي  2012   NaN    NaN
3   عدد الأطباء  جيبوتي  2013   NaN    NaN
4   عدد الأطباء  جيبوتي  2014   NaN    NaN
5   عدد الأطباء  جيبوتي  2015   NaN    NaN
6   عدد الأطباء  جيبوتي  2016   NaN    NaN
7   عدد الأطباء  جيبوتي  2017   NaN    NaN
8   عدد الأطباء  جيبوتي  2018   NaN    NaN
9   عدد الأطباء  جيبوتي  2019   NaN    NaN
10  عدد الأطباء  جيبوتي  2020   NaN    NaN
11  عدد الأطباء  جيبوتي  2021   NaN    NaN
12  عدد الأطباء  جيبوتي  2022   NaN    NaN
13  عدد الأطباء  جيبوتي  2023   NaN    NaN
14  عدد الأطباء  جيبوتي  2024   NaN    NaN
15  عدد الأطباء  جيبوتي  2025   NaN    NaN
16  عدد الأطباء  جيبوتي  2026   NaN    NaN
17  عدد الأطباء  جيبوتي  2027   NaN    NaN
18  عدد الأطباء  جيبوتي  2028   NaN    NaN
19  عدد الأطباء  جيبوتي  2029   NaN    NaN
20  عدد الأطباء  جيبوتي  2030   NaN    NaN

In [7]:
final_df.head()

,المؤشر,الدولة,الفئة العمرية,الجنس,السنة,العدد,المصدر,المواطنة,المنطقة,Unnamed: 19,Unnamed: 20
0,معدل انتشار التدخين (نسبة مئوية),الجزائر,15-24,كلا الجنسين,2010,NaN,NaN,NaN,NaN,NaN,NaN
1,معدل انتشار التدخين (نسبة مئوية),الجزائر,15-24,ذكور,2010,NaN,NaN,NaN,NaN,NaN,NaN
2,معدل انتشار التدخين (نسبة مئوية),الجزائر,15-24,إناث,2010,NaN,NaN,NaN,NaN,NaN,NaN
3,معدل انتشار التدخين (نسبة مئوية),الجزائر,جميع الأعمار,كلا الجنسين,2010,NaN,NaN,NaN,NaN,NaN,NaN
4,معدل انتشار التدخين (نسبة مئوية),الجزائر,جميع الأعمار,ذكور,2010,NaN,NaN,NaN,NaN,NaN,NaN

### check unique values in columns

In [ ]:
# #read in all files and combine into a single dataframe
# dataframes = []
# for file in xlsx_files:
#     df = pd.read_excel(os.path.join(folder_path, file))
#     #find the first row that is all empty (NaN)
#     separator_iloc = df[df.isnull().all(axis=1)].index[0]

#     #for data dataframe
#     df_data=df.iloc[1:separator_iloc , :].copy().reset_index(drop=True)
#     #reshape the data dataframe from wide to long
#     #id_vars are all colums that are not integers (years)
#     id_variables = [col for col in df_data.columns if not col.isdigit()]

#     df_data=df_data.melt(id_vars=id_variables, var_name='السنة', value_name='العدد')
#     #convert the 'السنة' column to numeric
#     df_data['السنة'] = df_data['السنة'].astype(int)
    

#     #for the source dataframe
#     # Find the header row for the 'source' table (df2).
#     source_header=df.iloc[separator_iloc + 1, :3].tolist()
#     #read in data
#     df_source=df.iloc[separator_iloc + 2:separator_iloc + 18, :3].copy().reset_index(drop=True)
#     #set the header
#     df_source.columns=source_header
#     df_source['السنة'] = df_source['السنة'].astype(int)
    
#     #merge the source with the data left on المؤشر, السنة
#     df_merged=pd.merge(df_data, df_source, on=['السنة'], how='left')

#     # #append to data list
#     dataframes.append(df_merged)

### do the same by using empty row to divide the two dataframes

In [ ]:
# #read in all files and combine into a single dataframe
# dataframes = []
# for file in xlsx_files:
#     df = pd.read_excel(os.path.join(folder_path, file))
#     #find the first row that is all empty (NaN)
#     separator_iloc = df[df.isnull().all(axis=1)].index[0]

#     #for data dataframe
#     df_data=df.iloc[1:separator_iloc , :].copy().reset_index(drop=True)
#     #reshape the data dataframe from wide to long
#     #id_vars are all colums that are not integers (years)
#     id_variables = [col for col in df_data.columns if not col.isdigit()]

#     df_data=df_data.melt(id_vars=id_variables, var_name='السنة', value_name='العدد')
#     #convert the 'السنة' column to numeric
#     df_data['السنة'] = df_data['السنة'].astype(int)
    

#     #for the source dataframe
#     # Find the header row for the 'source' table (df2).
#     source_header=df.iloc[separator_iloc + 1, :3].tolist()
#     #read in data
#     df_source=df.iloc[separator_iloc + 2:separator_iloc + 18, :3].copy().reset_index(drop=True)
#     #set the header
#     df_source.columns=source_header
#     df_source['السنة'] = df_source['السنة'].astype(int)
    
#     #merge the source with the data left on المؤشر, السنة
#     df_merged=pd.merge(df_data, df_source, on=['السنة'], how='left')

#     # #append to data list
#     dataframes.append(df_merged)